apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arthur-airport

resources:
  - neo4j.yaml
  - zookeeper.yaml
  - kafka.yaml
  - jaeger.yaml
  - prometheus.yaml
  - grafana.yaml
  - loki.yaml
