apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: arthur-airport
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: arthur-airport
    app.kubernetes.io/component: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
        app.kubernetes.io/name: loki
        app.kubernetes.io/part-of: arthur-airport
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.4
          args:
            - "-config.file=/etc/loki/local-config.yaml"
          ports:
            - containerPort: 3100
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: arthur-airport
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: arthur-airport
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
