/* ──────── Source metadata for display ──────── */

export const SOURCE_DESCRIPTIONS: Record<
  string,
  { label: string; description: string; icon: string }
> = {
  // Weather sources
  simulated: {
    label: "Simulated (FSM)",
    description: "Finite state machine with probabilistic transitions",
    icon: "🎲",
  },
  historical: {
    label: "Historical (CSV)",
    description: "Replay from real METAR observations (Iowa State Mesonet)",
    icon: "📜",
  },
  live: {
    label: "Live (ADDS API)",
    description: "Real-time from Aviation Weather Center aviationweather.gov",
    icon: "🌐",
  },
  // Flight sources
  "adsb.lol": {
    label: "adsb.lol",
    description: "Live ADS-B data from adsb.lol community API (free, no auth)",
    icon: "📡",
  },
  opensky: {
    label: "OpenSky Network (fallback)",
    description:
      "ADS-B data from OpenSky Network REST API — used as fallback when adsb.lol is unavailable",
    icon: "📡",
  },
  simulation: {
    label: "Simulation Engine",
    description: "Generated by sim-orchestrator with probabilistic models",
    icon: "⚙️",
  },
  disabled: { label: "Disabled", description: "Source not active", icon: "⏸️" },
  // Infrastructure sources
  ourairports: {
    label: "OurAirports",
    description:
      "Community-maintained open dataset — airport layouts, runways, frequencies, navaids",
    icon: "🛫",
  },
  // Passenger sources
  bts_historical: {
    label: "BTS Historical",
    description:
      "Bureau of Transportation Statistics historical passenger data",
    icon: "📊",
  },
  // Incident calibration sources
  asrs_historical: {
    label: "FAA ASRS calibrated",
    description:
      "Probabilities derived from FAA Aviation Safety Reporting System public summaries",
    icon: "🚨",
  },
};

export const TYPE_COLORS: Record<string, string> = {
  weather: "from-sky-500/20 to-blue-600/10 border-sky-500/30",
  flights: "from-cyan-500/20 to-teal-600/10 border-cyan-500/30",
  passengers: "from-violet-500/20 to-purple-600/10 border-violet-500/30",
  baggage: "from-amber-500/20 to-orange-600/10 border-amber-500/30",
  incidents: "from-red-500/20 to-rose-600/10 border-red-500/30",
};

export const STATUS_STYLES: Record<
  string,
  { bg: string; text: string; dot: string }
> = {
  active: {
    bg: "bg-emerald-900/40",
    text: "text-emerald-400",
    dot: "bg-emerald-400",
  },
  degraded: {
    bg: "bg-amber-900/40",
    text: "text-amber-400",
    dot: "bg-amber-400",
  },
  unavailable: {
    bg: "bg-red-900/40",
    text: "text-red-400",
    dot: "bg-red-400",
  },
};

export const COMPARE_FIELDS = [
  "category",
  "visibility_m",
  "wind_speed_kt",
  "wind_direction",
  "temperature_c",
  "qnh_hpa",
] as const;
export type CompareField = (typeof COMPARE_FIELDS)[number];

export const SOURCE_CHART_COLORS: Record<string, string> = {
  simulated: "#22d3ee",
  historical: "#fbbf24",
  live: "#34d399",
};

/* ──────── Shared types ──────── */

export interface CompareSource {
  available: boolean;
  reason?: string;
  category?: string;
  visibility_m?: number;
  wind_speed_kt?: number;
  wind_direction?: number;
  wind_gust_kt?: number | null;
  ceiling_ft?: number | null;
  temperature_c?: number;
  dew_point_c?: number;
  qnh_hpa?: number;
}

export interface CompareResult {
  sim_time: string | null;
  sources: Record<string, CompareSource>;
}

export interface HistoryEntry {
  timestamp: number;
  sources: Record<string, Record<string, number | string | null>>;
}
