import { useState, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  dataSourcesApi,
  weatherApi,
  type DataSourceStatus,
} from "../../hooks/useApi";

/* ──────── Source metadata for display ──────── */

const SOURCE_DESCRIPTIONS: Record<string, { label: string; description: string; icon: string }> = {
  // Weather sources
  simulated: { label: "Simulated (FSM)", description: "Finite state machine with probabilistic transitions", icon: "🎲" },
  historical: { label: "Historical (CSV)", description: "Replay from real METAR observations (Iowa State Mesonet)", icon: "📜" },
  live: { label: "Live (ADDS API)", description: "Real-time from Aviation Weather Center aviationweather.gov", icon: "🌐" },
  // Flight sources
  opensky: { label: "OpenSky Network", description: "Live ADS-B data from OpenSky Network REST API", icon: "📡" },
  simulation: { label: "Simulation Engine", description: "Generated by sim-orchestrator with probabilistic models", icon: "⚙️" },
  disabled: { label: "Disabled", description: "Source not active", icon: "⏸️" },
  // Passenger sources
  bts_historical: { label: "BTS Historical", description: "Bureau of Transportation Statistics historical passenger data", icon: "📊" },
};

const TYPE_COLORS: Record<string, string> = {
  weather: "from-sky-500/20 to-blue-600/10 border-sky-500/30",
  flights: "from-cyan-500/20 to-teal-600/10 border-cyan-500/30",
  passengers: "from-violet-500/20 to-purple-600/10 border-violet-500/30",
  baggage: "from-amber-500/20 to-orange-600/10 border-amber-500/30",
  incidents: "from-red-500/20 to-rose-600/10 border-red-500/30",
};

const STATUS_STYLES: Record<string, { bg: string; text: string; dot: string }> = {
  active: { bg: "bg-emerald-900/40", text: "text-emerald-400", dot: "bg-emerald-400" },
  degraded: { bg: "bg-amber-900/40", text: "text-amber-400", dot: "bg-amber-400" },
  unavailable: { bg: "bg-red-900/40", text: "text-red-400", dot: "bg-red-400" },
};

/* ──────── Weather Comparison Panel ──────── */

function WeatherComparisonPanel({ currentSource }: { currentSource: string }) {
  const [compareTo, setCompareTo] = useState<string | null>(null);
  const [comparisonData, setComparisonData] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(false);

  const currentWeather = useQuery({
    queryKey: ["weather-current-comparison"],
    queryFn: () => weatherApi.current(),
    refetchInterval: 15000,
  });

  const runComparison = async (targetSource: string) => {
    setLoading(true);
    setCompareTo(targetSource);
    try {
      // Switch to target source, get data, switch back
      await weatherApi.switchSource(targetSource);
      // Wait a moment for the source to produce data
      await new Promise((r) => setTimeout(r, 2000));
      const targetData = await weatherApi.current();
      // Switch back
      await weatherApi.switchSource(currentSource);
      setComparisonData(targetData as unknown as Record<string, unknown>);
    } catch (err) {
      setComparisonData({ error: String(err) });
      // Ensure we switch back
      await weatherApi.switchSource(currentSource).catch(() => {});
    } finally {
      setLoading(false);
    }
  };

  const currentData = currentWeather.data as Record<string, unknown> | undefined;
  const compareFields = ["category", "wind_speed_kt", "wind_direction_deg", "visibility_m", "temperature_c", "pressure_hpa"] as const;

  return (
    <div className="mt-4 p-4 rounded-xl bg-slate-800/60 border border-slate-700/50">
      <h3 className="text-sm font-semibold text-slate-200 mb-3">📊 Data Comparison</h3>

      <div className="flex items-center gap-2 mb-4">
        <span className="text-xs text-slate-400">Compare current ({currentSource}) with:</span>
        {["simulated", "historical", "live"]
          .filter((s) => s !== currentSource)
          .map((s) => (
            <button
              key={s}
              onClick={() => runComparison(s)}
              disabled={loading}
              className="px-3 py-1 text-xs rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-300
                         disabled:opacity-40 transition-colors border border-slate-600"
            >
              {SOURCE_DESCRIPTIONS[s]?.icon} {SOURCE_DESCRIPTIONS[s]?.label ?? s}
            </button>
          ))}
      </div>

      {loading && (
        <div className="text-xs text-slate-400 animate-pulse">Fetching comparison data...</div>
      )}

      {compareTo && comparisonData && !loading && (
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-slate-700">
                <th className="text-left py-2 px-2 text-slate-400 font-medium">Field</th>
                <th className="text-left py-2 px-2 text-slate-400 font-medium">
                  {SOURCE_DESCRIPTIONS[currentSource]?.icon} Current ({currentSource})
                </th>
                <th className="text-left py-2 px-2 text-slate-400 font-medium">
                  {SOURCE_DESCRIPTIONS[compareTo]?.icon} {compareTo}
                </th>
                <th className="text-left py-2 px-2 text-slate-400 font-medium">Δ Difference</th>
              </tr>
            </thead>
            <tbody>
              {compareFields.map((field) => {
                const currentVal = currentData?.[field];
                const compareVal = comparisonData?.[field];
                const isDifferent = currentVal !== compareVal;
                const numDiff =
                  typeof currentVal === "number" && typeof compareVal === "number"
                    ? Math.round((compareVal - currentVal) * 10) / 10
                    : null;

                return (
                  <tr key={field} className={`border-b border-slate-800 ${isDifferent ? "bg-amber-900/10" : ""}`}>
                    <td className="py-1.5 px-2 font-mono text-slate-300">{field}</td>
                    <td className="py-1.5 px-2 text-slate-200">{String(currentVal ?? "—")}</td>
                    <td className="py-1.5 px-2 text-slate-200">{String(compareVal ?? "—")}</td>
                    <td className="py-1.5 px-2">
                      {isDifferent ? (
                        <span className={numDiff !== null ? (numDiff > 0 ? "text-red-400" : "text-green-400") : "text-amber-400"}>
                          {numDiff !== null ? `${numDiff > 0 ? "+" : ""}${numDiff}` : "≠"}
                        </span>
                      ) : (
                        <span className="text-slate-600">—</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

/* ──────── Source Card ──────── */

function SourceCard({
  source,
  onSwitch,
  isSwitching,
}: {
  source: DataSourceStatus;
  onSwitch: (sourceId: string, newSource: string) => void;
  isSwitching: boolean;
}) {
  const [expanded, setExpanded] = useState(false);
  const statusStyle = STATUS_STYLES[source.status] ?? STATUS_STYLES.unavailable;
  const typeColor = TYPE_COLORS[source.type] ?? TYPE_COLORS.weather;
  const sourceInfo = SOURCE_DESCRIPTIONS[source.current_source] ?? {
    label: source.current_source,
    description: "Unknown source",
    icon: "❓",
  };

  return (
    <div className={`rounded-xl border bg-gradient-to-br ${typeColor} p-4 transition-all duration-200 hover:shadow-lg hover:shadow-black/20`}>
      {/* Header */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-3">
          <div className="text-2xl">{sourceInfo.icon}</div>
          <div>
            <h3 className="text-sm font-semibold text-slate-100">{source.name}</h3>
            <p className="text-xs text-slate-400">{source.service}</p>
          </div>
        </div>
        <div className={`flex items-center gap-1.5 px-2 py-0.5 rounded-full ${statusStyle.bg}`}>
          <span className={`w-1.5 h-1.5 rounded-full ${statusStyle.dot} animate-pulse`} />
          <span className={`text-[10px] font-semibold uppercase ${statusStyle.text}`}>
            {source.status}
          </span>
        </div>
      </div>

      {/* Current source info */}
      <div className="mb-3 p-2 rounded-lg bg-slate-900/50">
        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-400">Active:</span>
          <span className="text-xs font-semibold text-slate-200">{sourceInfo.label}</span>
        </div>
        <p className="text-[10px] text-slate-500 mt-0.5">{sourceInfo.description}</p>
      </div>

      {/* Available sources */}
      {source.available_sources.length > 1 && (
        <div className="mb-3">
          <p className="text-[10px] text-slate-400 mb-1.5 uppercase tracking-wide font-semibold">Switch source:</p>
          <div className="flex flex-wrap gap-1.5">
            {source.available_sources.map((s) => {
              const isActive = s === source.current_source;
              const sInfo = SOURCE_DESCRIPTIONS[s] ?? { label: s, icon: "❓" };
              return (
                <button
                  key={s}
                  disabled={isActive || isSwitching || source.id !== "weather"}
                  onClick={() => onSwitch(source.id, s)}
                  className={`px-2.5 py-1 text-[11px] rounded-lg transition-all border ${
                    isActive
                      ? "bg-accent/20 text-accent border-accent/40 cursor-default"
                      : source.id === "weather"
                        ? "bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700 hover:border-slate-500"
                        : "bg-slate-800/50 text-slate-500 border-slate-700/50 cursor-not-allowed"
                  }`}
                  title={source.id !== "weather" && !isActive ? "Source switching not yet implemented for this service" : ""}
                >
                  {sInfo.icon} {sInfo.label}
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Details toggle */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="text-[10px] text-slate-400 hover:text-slate-200 transition-colors"
      >
        {expanded ? "▾ Hide details" : "▸ Show details"}
      </button>

      {expanded && (
        <div className="mt-2 p-2 rounded-lg bg-slate-900/40 border border-slate-700/30">
          <pre className="text-[10px] text-slate-400 font-mono whitespace-pre-wrap overflow-x-auto">
            {JSON.stringify(source.details, null, 2)}
          </pre>
          {source.last_updated && (
            <p className="text-[10px] text-slate-500 mt-1">
              Last updated: {new Date(source.last_updated).toLocaleTimeString()}
            </p>
          )}
        </div>
      )}

      {/* Weather comparison panel */}
      {source.id === "weather" && source.status === "active" && (
        <WeatherComparisonPanel currentSource={source.current_source} />
      )}
    </div>
  );
}

/* ──────── Integration Guide Panel ──────── */

function IntegrationGuide() {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="rounded-xl border border-slate-700/50 bg-slate-800/40 p-4">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between"
      >
        <div className="flex items-center gap-2">
          <span className="text-lg">📖</span>
          <h3 className="text-sm font-semibold text-slate-200">Adding New Data Sources</h3>
        </div>
        <span className={`text-slate-400 transition-transform ${expanded ? "rotate-180" : ""}`}>▾</span>
      </button>

      {expanded && (
        <div className="mt-4 text-xs text-slate-300 space-y-4">
          <div className="p-3 rounded-lg bg-slate-900/50 border border-slate-700/30">
            <h4 className="font-semibold text-slate-100 mb-2">Architecture Overview</h4>
            <p className="text-slate-400 leading-relaxed">
              Each data source is implemented as a <strong>provider adapter</strong> inside the relevant service.
              The adapter transforms external data into the canonical event/entity format defined in{" "}
              <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">docs/architecture/EVENT_BUS.md</code> and{" "}
              <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">docs/architecture/DATA_MODEL.md</code>.
            </p>
          </div>

          <div className="p-3 rounded-lg bg-slate-900/50 border border-slate-700/30">
            <h4 className="font-semibold text-slate-100 mb-2">Steps to Add a New Source</h4>
            <ol className="list-decimal list-inside space-y-2 text-slate-400">
              <li>
                <strong className="text-slate-200">Create adapter class</strong> in{" "}
                <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">services/&lt;name&gt;/services/</code>{" "}
                implementing the provider interface (see <code>HistoricalMetarSource</code> or <code>LiveMetarSource</code> as examples)
              </li>
              <li>
                <strong className="text-slate-200">Register in consumer</strong> — add source selection logic in the Kafka consumer&apos;s dispatch method
              </li>
              <li>
                <strong className="text-slate-200">Add env var</strong> — define configuration in docker-compose and document in{" "}
                <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">docs/infra/DOCKER.md</code>
              </li>
              <li>
                <strong className="text-slate-200">Expose /source endpoint</strong> — add GET/POST endpoints for status and runtime switching
              </li>
              <li>
                <strong className="text-slate-200">Update gateway</strong> — add to{" "}
                <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">services/api-gateway/src/dataSources.ts</code>
              </li>
              <li>
                <strong className="text-slate-200">Update this page</strong> — add source metadata to{" "}
                <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">SOURCE_DESCRIPTIONS</code> in DataSourcesPage.tsx
              </li>
            </ol>
          </div>

          <div className="p-3 rounded-lg bg-slate-900/50 border border-slate-700/30">
            <h4 className="font-semibold text-slate-100 mb-2">Example: Adding BTS Passenger Data</h4>
            <div className="font-mono text-[10px] text-slate-400 space-y-1">
              <p className="text-slate-500"># 1. Create adapter</p>
              <p>services/passenger-service/services/bts_adapter.py</p>
              <p className="text-slate-500 mt-2"># 2. Implement interface</p>
              <p>class BTSPassengerSource:</p>
              <p>&nbsp;&nbsp;def load(self, csv_path: str) -&gt; int: ...</p>
              <p>&nbsp;&nbsp;def get_flow_at(self, sim_time: datetime) -&gt; PassengerFlow: ...</p>
              <p className="text-slate-500 mt-2"># 3. Register in consumer.py</p>
              <p>if self.passenger_source == &quot;bts_historical&quot;:</p>
              <p>&nbsp;&nbsp;self._bts = BTSPassengerSource(csv_path)</p>
              <p className="text-slate-500 mt-2"># 4. Add env var in docker-compose.yml</p>
              <p>PASSENGER_SOURCE=simulation  # or bts_historical</p>
              <p>PASSENGER_BTS_FILE=/app/data/bts/T100_2023.csv</p>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-emerald-900/20 border border-emerald-700/30">
            <h4 className="font-semibold text-emerald-300 mb-1">Key Principle</h4>
            <p className="text-slate-400 leading-relaxed">
              Downstream services remain unchanged. Any source adapter publishes the same canonical Kafka events
              and writes the same Neo4j entity shape. The adapter is a thin translation layer at the system edge.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

/* ──────── Main Page ──────── */

export default function DataSourcesPage() {
  const queryClient = useQueryClient();

  const { data, isLoading, error } = useQuery({
    queryKey: ["data-sources"],
    queryFn: () => dataSourcesApi.list(),
    refetchInterval: 15000,
  });

  const switchMutation = useMutation({
    mutationFn: ({ source }: { sourceId: string; source: string }) =>
      dataSourcesApi.switchWeatherSource(source),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["data-sources"] });
      queryClient.invalidateQueries({ queryKey: ["weather-source"] });
    },
  });

  const sources = data?.sources ?? [];

  const stats = useMemo(() => {
    const active = sources.filter((s) => s.status === "active").length;
    const degraded = sources.filter((s) => s.status === "degraded").length;
    const unavailable = sources.filter((s) => s.status === "unavailable").length;
    const realSources = sources.filter(
      (s) => s.current_source !== "simulation" && s.current_source !== "simulated" && s.current_source !== "disabled",
    ).length;
    return { active, degraded, unavailable, total: sources.length, realSources };
  }, [sources]);

  const handleSwitch = (sourceId: string, newSource: string) => {
    switchMutation.mutate({ sourceId, source: newSource });
  };

  return (
    <div className="h-full overflow-y-auto p-4 sm:p-6 space-y-6">
      {/* Page Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-lg font-bold text-slate-100 flex items-center gap-2">
            <span className="text-xl">🔌</span> Data Sources
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Manage and monitor data providers feeding the digital twin. Switch between simulation and real-world sources at runtime.
          </p>
        </div>
        {data && (
          <div className="text-[10px] text-slate-500">
            Last refresh: {new Date(data.timestamp).toLocaleTimeString()}
          </div>
        )}
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
        <div className="rounded-xl bg-slate-800/60 border border-slate-700/40 p-3 text-center">
          <div className="text-lg font-bold text-slate-100">{stats.total}</div>
          <div className="text-[10px] text-slate-400 uppercase tracking-wide">Total Sources</div>
        </div>
        <div className="rounded-xl bg-emerald-900/30 border border-emerald-700/30 p-3 text-center">
          <div className="text-lg font-bold text-emerald-400">{stats.active}</div>
          <div className="text-[10px] text-emerald-400/70 uppercase tracking-wide">Active</div>
        </div>
        <div className="rounded-xl bg-amber-900/30 border border-amber-700/30 p-3 text-center">
          <div className="text-lg font-bold text-amber-400">{stats.degraded}</div>
          <div className="text-[10px] text-amber-400/70 uppercase tracking-wide">Degraded</div>
        </div>
        <div className="rounded-xl bg-red-900/30 border border-red-700/30 p-3 text-center">
          <div className="text-lg font-bold text-red-400">{stats.unavailable}</div>
          <div className="text-[10px] text-red-400/70 uppercase tracking-wide">Unavailable</div>
        </div>
        <div className="rounded-xl bg-cyan-900/30 border border-cyan-700/30 p-3 text-center">
          <div className="text-lg font-bold text-cyan-400">{stats.realSources}</div>
          <div className="text-[10px] text-cyan-400/70 uppercase tracking-wide">Real-World</div>
        </div>
      </div>

      {/* Error state */}
      {error && (
        <div className="rounded-xl bg-red-900/20 border border-red-700/40 p-4 text-sm text-red-300">
          Failed to load data sources: {(error as Error).message}
        </div>
      )}

      {/* Loading state */}
      {isLoading && (
        <div className="text-center text-slate-400 text-sm py-8 animate-pulse">
          Loading data sources...
        </div>
      )}

      {/* Source Cards Grid */}
      {!isLoading && sources.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {sources.map((source) => (
            <SourceCard
              key={source.id}
              source={source}
              onSwitch={handleSwitch}
              isSwitching={switchMutation.isPending}
            />
          ))}
        </div>
      )}

      {/* Switching feedback */}
      {switchMutation.isPending && (
        <div className="fixed bottom-4 right-4 rounded-xl bg-blue-900/90 border border-blue-600/50 px-4 py-3 text-sm text-blue-200 shadow-xl backdrop-blur-sm animate-pulse">
          Switching data source...
        </div>
      )}
      {switchMutation.isError && (
        <div className="fixed bottom-4 right-4 rounded-xl bg-red-900/90 border border-red-600/50 px-4 py-3 text-sm text-red-200 shadow-xl backdrop-blur-sm">
          Switch failed: {(switchMutation.error as Error).message}
        </div>
      )}

      {/* Integration Guide */}
      <IntegrationGuide />
    </div>
  );
}
