import { useState, useMemo, useCallback, useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  dataSourcesApi,
  weatherApi,
  type DataSourceStatus,
} from "../../hooks/useApi";
import { useWeatherStore } from "../../stores/weatherStore";
import type { WeatherState } from "../../types";

/* ──────── Source metadata for display ──────── */

const SOURCE_DESCRIPTIONS: Record<
  string,
  { label: string; description: string; icon: string }
> = {
  // Weather sources
  simulated: {
    label: "Simulated (FSM)",
    description: "Finite state machine with probabilistic transitions",
    icon: "🎲",
  },
  historical: {
    label: "Historical (CSV)",
    description: "Replay from real METAR observations (Iowa State Mesonet)",
    icon: "📜",
  },
  live: {
    label: "Live (ADDS API)",
    description: "Real-time from Aviation Weather Center aviationweather.gov",
    icon: "🌐",
  },
  // Flight sources
  opensky: {
    label: "OpenSky Network",
    description: "Live ADS-B data from OpenSky Network REST API",
    icon: "📡",
  },
  simulation: {
    label: "Simulation Engine",
    description: "Generated by sim-orchestrator with probabilistic models",
    icon: "⚙️",
  },
  disabled: { label: "Disabled", description: "Source not active", icon: "⏸️" },
  // Passenger sources
  bts_historical: {
    label: "BTS Historical",
    description:
      "Bureau of Transportation Statistics historical passenger data",
    icon: "📊",
  },
};

const TYPE_COLORS: Record<string, string> = {
  weather: "from-sky-500/20 to-blue-600/10 border-sky-500/30",
  flights: "from-cyan-500/20 to-teal-600/10 border-cyan-500/30",
  passengers: "from-violet-500/20 to-purple-600/10 border-violet-500/30",
  baggage: "from-amber-500/20 to-orange-600/10 border-amber-500/30",
  incidents: "from-red-500/20 to-rose-600/10 border-red-500/30",
};

const STATUS_STYLES: Record<string, { bg: string; text: string; dot: string }> =
  {
    active: {
      bg: "bg-emerald-900/40",
      text: "text-emerald-400",
      dot: "bg-emerald-400",
    },
    degraded: {
      bg: "bg-amber-900/40",
      text: "text-amber-400",
      dot: "bg-amber-400",
    },
    unavailable: {
      bg: "bg-red-900/40",
      text: "text-red-400",
      dot: "bg-red-400",
    },
  };

/* ──────── Weather Comparison Panel ──────── */

interface CompareSource {
  available: boolean;
  reason?: string;
  category?: string;
  visibility_m?: number;
  wind_speed_kt?: number;
  wind_direction?: number;
  wind_gust_kt?: number | null;
  ceiling_ft?: number | null;
  temperature_c?: number;
  dew_point_c?: number;
  qnh_hpa?: number;
}

interface CompareResult {
  sim_time: string | null;
  sources: Record<string, CompareSource>;
}

interface HistoryEntry {
  timestamp: number;
  sources: Record<string, Record<string, number | string | null>>;
}

const COMPARE_FIELDS = [
  "category",
  "visibility_m",
  "wind_speed_kt",
  "wind_direction",
  "temperature_c",
  "qnh_hpa",
] as const;
type CompareField = (typeof COMPARE_FIELDS)[number];

function WeatherComparisonPanel({ currentSource }: { currentSource: string }) {
  const [comparison, setComparison] = useState<CompareResult | null>(null);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [loading, setLoading] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [chartField, setChartField] = useState<string>("temperature_c");

  const fetchComparison = useCallback(async () => {
    setLoading(true);
    try {
      const data = (await weatherApi.compare()) as CompareResult;
      setComparison(data);
      // Append to history for graphing
      if (data.sim_time) {
        setHistory((prev) => {
          const entry: HistoryEntry = {
            timestamp: Date.now(),
            sources: {},
          };
          for (const [src, vals] of Object.entries(data.sources)) {
            if (vals.available) {
              entry.sources[src] = {};
              for (const f of COMPARE_FIELDS) {
                entry.sources[src][f] = vals[f as CompareField] ?? null;
              }
            }
          }
          const next = [...prev, entry];
          // Keep last 60 data points (~15 min at 15s interval)
          return next.slice(-60);
        });
      }
    } catch {
      /* ignore */
    } finally {
      setLoading(false);
    }
  }, []);

  // Auto-refresh every 15 seconds
  useEffect(() => {
    fetchComparison();
    const interval = setInterval(fetchComparison, 15000);
    return () => clearInterval(interval);
  }, [fetchComparison]);

  const sourceNames = comparison
    ? Object.keys(comparison.sources)
    : ["simulated", "historical", "live"];

  const SOURCE_COLORS: Record<string, string> = {
    simulated: "text-cyan-400",
    historical: "text-amber-400",
    live: "text-emerald-400",
  };

  return (
    <div className="mt-4 p-4 rounded-xl bg-slate-800/60 border border-slate-700/50">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-semibold text-slate-200">
          📊 Source Comparison
        </h3>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowModal(true)}
            className="text-[10px] px-2 py-1 rounded bg-slate-700 hover:bg-slate-600 text-slate-300 transition-colors"
          >
            📈 Chart
          </button>
          <button
            onClick={fetchComparison}
            disabled={loading}
            className="text-[10px] px-2 py-1 rounded bg-slate-700 hover:bg-slate-600 text-slate-300 transition-colors disabled:opacity-40"
          >
            {loading ? "..." : "↻ Refresh"}
          </button>
        </div>
      </div>

      <p className="text-[10px] text-slate-500 mb-3">
        Non-destructive comparison — reads from all sources without switching
        the active one. Active:{" "}
        <span className="text-slate-300">{currentSource}</span>
      </p>

      {/* Table view — always visible */}
      {comparison && (
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-slate-700">
                <th className="text-left py-2 px-2 text-slate-400 font-medium">
                  Field
                </th>
                {sourceNames.map((src) => (
                  <th
                    key={src}
                    className={`text-left py-2 px-2 font-medium ${SOURCE_COLORS[src] ?? "text-slate-400"}`}
                  >
                    {SOURCE_DESCRIPTIONS[src]?.icon ?? "❓"}{" "}
                    {SOURCE_DESCRIPTIONS[src]?.label ?? src}
                    {src === currentSource && (
                      <span className="ml-1 text-[8px] bg-accent/20 text-accent px-1 rounded">
                        active
                      </span>
                    )}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {COMPARE_FIELDS.map((field) => {
                const values = sourceNames.map(
                  (src) =>
                    (
                      comparison.sources[src] as unknown as Record<
                        string,
                        unknown
                      >
                    )?.[field],
                );
                const allSame =
                  values.every((v) => v === values[0]) &&
                  values.every((v) => v != null);
                const numValues = values.filter(
                  (v) => typeof v === "number",
                ) as number[];
                const maxDiff =
                  numValues.length >= 2
                    ? Math.round(
                        (Math.max(...numValues) - Math.min(...numValues)) * 10,
                      ) / 10
                    : null;

                return (
                  <tr
                    key={field}
                    className={`border-b border-slate-800 ${!allSame ? "bg-amber-900/10" : ""}`}
                  >
                    <td className="py-1.5 px-2 font-mono text-slate-300">
                      {field}
                    </td>
                    {sourceNames.map((src) => {
                      const srcData = comparison.sources[src];
                      if (!srcData?.available) {
                        return (
                          <td
                            key={src}
                            className="py-1.5 px-2 text-slate-600 italic"
                          >
                            N/A
                          </td>
                        );
                      }
                      return (
                        <td key={src} className="py-1.5 px-2 text-slate-200">
                          {String(
                            (srcData as unknown as Record<string, unknown>)?.[
                              field
                            ] ?? "—",
                          )}
                        </td>
                      );
                    })}
                    {maxDiff !== null && !allSame && (
                      <td className="py-1.5 px-2 text-amber-400 text-[10px]">
                        Δ{maxDiff}
                      </td>
                    )}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Chart modal */}
      {showModal &&
        createPortal(
          <ComparisonModal
            history={history}
            comparison={comparison}
            chartField={chartField}
            setChartField={setChartField}
            sourceNames={sourceNames}
            currentSource={currentSource}
            onClose={() => setShowModal(false)}
          />,
          document.body,
        )}

      {!comparison && !loading && (
        <div className="text-xs text-slate-500 py-3 text-center">
          Click Refresh to compare weather across all sources.
        </div>
      )}
    </div>
  );
}

/* ──────── Mini SVG Chart for source comparison ──────── */
function MiniChart({
  history,
  field,
  sourceColors,
}: {
  history: HistoryEntry[];
  field: string;
  sourceColors: Record<string, string>;
}) {
  const sources = ["simulated", "historical", "live"];
  const width = 400;
  const height = 100;
  const pad = { top: 5, right: 5, bottom: 5, left: 35 };

  // Collect all values to compute y-axis range
  let allValues: number[] = [];
  for (const entry of history) {
    for (const src of sources) {
      const val = entry.sources[src]?.[field];
      if (typeof val === "number") allValues.push(val);
    }
  }
  if (allValues.length === 0) allValues = [0, 1];

  const yMin = Math.min(...allValues);
  const yMax = Math.max(...allValues);
  const yRange = yMax - yMin || 1;

  const xScale = (i: number) =>
    pad.left +
    (i / Math.max(1, history.length - 1)) * (width - pad.left - pad.right);
  const yScale = (v: number) =>
    pad.top + (1 - (v - yMin) / yRange) * (height - pad.top - pad.bottom);

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      className="w-full h-full"
      preserveAspectRatio="none"
    >
      {/* Y-axis labels */}
      <text
        x={pad.left - 3}
        y={pad.top + 4}
        textAnchor="end"
        className="fill-slate-500"
        fontSize="8"
      >
        {typeof yMax === "number" ? yMax.toFixed(1) : ""}
      </text>
      <text
        x={pad.left - 3}
        y={height - pad.bottom}
        textAnchor="end"
        className="fill-slate-500"
        fontSize="8"
      >
        {typeof yMin === "number" ? yMin.toFixed(1) : ""}
      </text>

      {/* Lines for each source */}
      {sources.map((src) => {
        const points = history
          .map((entry, i) => {
            const val = entry.sources[src]?.[field];
            if (typeof val !== "number") return null;
            return `${xScale(i)},${yScale(val)}`;
          })
          .filter(Boolean);

        if (points.length < 2) return null;

        return (
          <polyline
            key={src}
            points={points.join(" ")}
            fill="none"
            stroke={sourceColors[src] ?? "#888"}
            strokeWidth="2"
            strokeLinejoin="round"
          />
        );
      })}
    </svg>
  );
}

/* ──────── Comparison Modal ──────── */

const SOURCE_CHART_COLORS: Record<string, string> = {
  simulated: "#22d3ee",
  historical: "#fbbf24",
  live: "#34d399",
};

function ComparisonModal({
  history,
  comparison,
  chartField,
  setChartField,
  sourceNames,
  currentSource,
  onClose,
}: {
  history: HistoryEntry[];
  comparison: CompareResult | null;
  chartField: string;
  setChartField: (f: string) => void;
  sourceNames: string[];
  currentSource: string;
  onClose: () => void;
}) {
  const backdropRef = useRef<HTMLDivElement>(null);

  return (
    <div
      ref={backdropRef}
      className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/70 backdrop-blur-sm"
      onClick={(e) => {
        if (e.target === backdropRef.current) onClose();
      }}
    >
      <div className="w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-xl bg-slate-900 border border-slate-700 shadow-2xl p-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-slate-100">
            📊 Weather Source Comparison
          </h2>
          <button
            onClick={onClose}
            className="px-3 py-1 rounded bg-slate-700 hover:bg-slate-600 text-slate-300 text-sm"
          >
            ✕ Close
          </button>
        </div>

        {/* Field selector */}
        <div className="flex items-center gap-3 mb-4">
          <span className="text-xs text-slate-400">Chart field:</span>
          <select
            value={chartField}
            onChange={(e) => setChartField(e.target.value)}
            className="text-xs bg-slate-800 text-slate-200 rounded px-3 py-1.5 border border-slate-600"
          >
            {COMPARE_FIELDS.filter((f) => f !== "category").map((f) => (
              <option key={f} value={f}>
                {f}
              </option>
            ))}
          </select>
        </div>

        {/* Large chart */}
        {history.length < 2 ? (
          <div className="text-sm text-slate-500 py-8 text-center bg-slate-800/50 rounded-lg">
            Collecting data points… Chart will appear after 2+ comparisons
            (auto-refreshes every 15s).
          </div>
        ) : (
          <div className="relative h-64 bg-slate-800/50 rounded-lg p-3 mb-4">
            <MiniChart
              history={history}
              field={chartField}
              sourceColors={SOURCE_CHART_COLORS}
            />
          </div>
        )}

        {/* Legend */}
        <div className="flex items-center gap-6 mb-6 justify-center">
          {sourceNames.map((src) => (
            <div
              key={src}
              className="flex items-center gap-2 text-xs text-slate-400"
            >
              <span
                className="w-3 h-3 rounded-full"
                style={{
                  backgroundColor: SOURCE_CHART_COLORS[src] ?? "#888",
                }}
              />
              {SOURCE_DESCRIPTIONS[src]?.label ?? src}
              {src === currentSource && (
                <span className="text-[9px] bg-accent/20 text-accent px-1 rounded">
                  active
                </span>
              )}
            </div>
          ))}
        </div>

        {/* Full comparison table */}
        {comparison && (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-700">
                  <th className="text-left py-2 px-3 text-slate-400 font-medium">
                    Field
                  </th>
                  {sourceNames.map((src) => (
                    <th
                      key={src}
                      className="text-left py-2 px-3 font-medium"
                      style={{ color: SOURCE_CHART_COLORS[src] ?? "#94a3b8" }}
                    >
                      {SOURCE_DESCRIPTIONS[src]?.icon ?? "❓"}{" "}
                      {SOURCE_DESCRIPTIONS[src]?.label ?? src}
                    </th>
                  ))}
                  <th className="text-left py-2 px-3 text-slate-400 font-medium">
                    Δ max
                  </th>
                </tr>
              </thead>
              <tbody>
                {COMPARE_FIELDS.map((field) => {
                  const values = sourceNames.map(
                    (src) =>
                      (
                        comparison.sources[src] as unknown as Record<
                          string,
                          unknown
                        >
                      )?.[field],
                  );
                  const allSame =
                    values.every((v) => v === values[0]) &&
                    values.every((v) => v != null);
                  const numValues = values.filter(
                    (v) => typeof v === "number",
                  ) as number[];
                  const maxDiff =
                    numValues.length >= 2
                      ? Math.round(
                          (Math.max(...numValues) - Math.min(...numValues)) *
                            10,
                        ) / 10
                      : null;

                  return (
                    <tr
                      key={field}
                      className={`border-b border-slate-800 ${!allSame ? "bg-amber-900/10" : ""}`}
                    >
                      <td className="py-2 px-3 font-mono text-slate-300">
                        {field}
                      </td>
                      {sourceNames.map((src) => {
                        const srcData = comparison.sources[src];
                        if (!srcData?.available) {
                          return (
                            <td
                              key={src}
                              className="py-2 px-3 text-slate-600 italic"
                            >
                              N/A
                            </td>
                          );
                        }
                        return (
                          <td key={src} className="py-2 px-3 text-slate-200">
                            {String(
                              (srcData as unknown as Record<string, unknown>)?.[
                                field
                              ] ?? "—",
                            )}
                          </td>
                        );
                      })}
                      <td className="py-2 px-3 text-amber-400 text-xs">
                        {maxDiff !== null && !allSame ? `Δ${maxDiff}` : "—"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

/* ──────── Source Card ──────── */

function SourceCard({
  source,
  onSwitch,
  isSwitching,
}: {
  source: DataSourceStatus;
  onSwitch: (sourceId: string, newSource: string) => void;
  isSwitching: boolean;
}) {
  const [expanded, setExpanded] = useState(false);
  const statusStyle = STATUS_STYLES[source.status] ?? STATUS_STYLES.unavailable;
  const typeColor = TYPE_COLORS[source.type] ?? TYPE_COLORS.weather;
  const sourceInfo = SOURCE_DESCRIPTIONS[source.current_source] ?? {
    label: source.current_source,
    description: "Unknown source",
    icon: "❓",
  };

  return (
    <div
      className={`rounded-xl border bg-gradient-to-br ${typeColor} p-4 transition-all duration-200 hover:shadow-lg hover:shadow-black/20`}
    >
      {/* Header */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-3">
          <div className="text-2xl">{sourceInfo.icon}</div>
          <div>
            <h3 className="text-sm font-semibold text-slate-100">
              {source.name}
            </h3>
            <p className="text-xs text-slate-400">{source.service}</p>
          </div>
        </div>
        <div
          className={`flex items-center gap-1.5 px-2 py-0.5 rounded-full ${statusStyle.bg}`}
        >
          <span
            className={`w-1.5 h-1.5 rounded-full ${statusStyle.dot} animate-pulse`}
          />
          <span
            className={`text-[10px] font-semibold uppercase ${statusStyle.text}`}
          >
            {source.status}
          </span>
        </div>
      </div>

      {/* Current source info */}
      <div className="mb-3 p-2 rounded-lg bg-slate-900/50">
        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-400">Active:</span>
          <span className="text-xs font-semibold text-slate-200">
            {sourceInfo.label}
          </span>
        </div>
        <p className="text-[10px] text-slate-500 mt-0.5">
          {sourceInfo.description}
        </p>
      </div>

      {/* Available sources */}
      {source.available_sources.length > 1 && (
        <div className="mb-3">
          <p className="text-[10px] text-slate-400 mb-1.5 uppercase tracking-wide font-semibold">
            Switch source:
          </p>
          <div className="flex flex-wrap gap-1.5">
            {source.available_sources.map((s) => {
              const isActive = s === source.current_source;
              const sInfo = SOURCE_DESCRIPTIONS[s] ?? { label: s, icon: "❓" };
              return (
                <button
                  key={s}
                  disabled={isActive || isSwitching || source.id !== "weather"}
                  onClick={() => onSwitch(source.id, s)}
                  className={`px-2.5 py-1 text-[11px] rounded-lg transition-all border ${
                    isActive
                      ? "bg-accent/20 text-accent border-accent/40 cursor-default"
                      : source.id === "weather"
                        ? "bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700 hover:border-slate-500"
                        : "bg-slate-800/50 text-slate-500 border-slate-700/50 cursor-not-allowed"
                  }`}
                  title={
                    source.id !== "weather" && !isActive
                      ? "Source switching not yet implemented for this service"
                      : ""
                  }
                >
                  {sInfo.icon} {sInfo.label}
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Details toggle */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="text-[10px] text-slate-400 hover:text-slate-200 transition-colors"
      >
        {expanded ? "▾ Hide details" : "▸ Show details"}
      </button>

      {expanded && (
        <div className="mt-2 p-2 rounded-lg bg-slate-900/40 border border-slate-700/30">
          <pre className="text-[10px] text-slate-400 font-mono whitespace-pre-wrap overflow-x-auto">
            {JSON.stringify(source.details, null, 2)}
          </pre>
          {source.last_updated && (
            <p className="text-[10px] text-slate-500 mt-1">
              Last updated: {new Date(source.last_updated).toLocaleTimeString()}
            </p>
          )}
        </div>
      )}

      {/* Weather comparison panel */}
      {source.id === "weather" && source.status === "active" && (
        <WeatherComparisonPanel currentSource={source.current_source} />
      )}
    </div>
  );
}

/* ──────── Integration Guide Panel ──────── */

function IntegrationGuide() {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="rounded-xl border border-slate-700/50 bg-slate-800/40 p-4">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between"
      >
        <div className="flex items-center gap-2">
          <span className="text-lg">📖</span>
          <h3 className="text-sm font-semibold text-slate-200">
            Adding New Data Sources
          </h3>
        </div>
        <span
          className={`text-slate-400 transition-transform ${expanded ? "rotate-180" : ""}`}
        >
          ▾
        </span>
      </button>

      {expanded && (
        <div className="mt-4 text-xs text-slate-300 space-y-4">
          <div className="p-3 rounded-lg bg-slate-900/50 border border-slate-700/30">
            <h4 className="font-semibold text-slate-100 mb-2">
              Architecture Overview
            </h4>
            <p className="text-slate-400 leading-relaxed">
              Each data source is implemented as a{" "}
              <strong>provider adapter</strong> inside the relevant service. The
              adapter transforms external data into the canonical event/entity
              format defined in{" "}
              <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">
                docs/architecture/EVENT_BUS.md
              </code>{" "}
              and{" "}
              <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">
                docs/architecture/DATA_MODEL.md
              </code>
              .
            </p>
          </div>

          <div className="p-3 rounded-lg bg-slate-900/50 border border-slate-700/30">
            <h4 className="font-semibold text-slate-100 mb-2">
              Steps to Add a New Source
            </h4>
            <ol className="list-decimal list-inside space-y-2 text-slate-400">
              <li>
                <strong className="text-slate-200">Create adapter class</strong>{" "}
                in{" "}
                <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">
                  services/&lt;name&gt;/services/
                </code>{" "}
                implementing the provider interface (see{" "}
                <code>HistoricalMetarSource</code> or{" "}
                <code>LiveMetarSource</code> as examples)
              </li>
              <li>
                <strong className="text-slate-200">Register in consumer</strong>{" "}
                — add source selection logic in the Kafka consumer&apos;s
                dispatch method
              </li>
              <li>
                <strong className="text-slate-200">Add env var</strong> — define
                configuration in docker-compose and document in{" "}
                <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">
                  docs/infra/DOCKER.md
                </code>
              </li>
              <li>
                <strong className="text-slate-200">
                  Expose /source endpoint
                </strong>{" "}
                — add GET/POST endpoints for status and runtime switching
              </li>
              <li>
                <strong className="text-slate-200">Update gateway</strong> — add
                to{" "}
                <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">
                  services/api-gateway/src/dataSources.ts
                </code>
              </li>
              <li>
                <strong className="text-slate-200">Update this page</strong> —
                add source metadata to{" "}
                <code className="px-1 py-0.5 bg-slate-800 rounded text-cyan-300">
                  SOURCE_DESCRIPTIONS
                </code>{" "}
                in DataSourcesPage.tsx
              </li>
            </ol>
          </div>

          <div className="p-3 rounded-lg bg-slate-900/50 border border-slate-700/30">
            <h4 className="font-semibold text-slate-100 mb-2">
              Example: Adding BTS Passenger Data
            </h4>
            <div className="font-mono text-[10px] text-slate-400 space-y-1">
              <p className="text-slate-500"># 1. Create adapter</p>
              <p>services/passenger-service/services/bts_adapter.py</p>
              <p className="text-slate-500 mt-2"># 2. Implement interface</p>
              <p>class BTSPassengerSource:</p>
              <p>&nbsp;&nbsp;def load(self, csv_path: str) -&gt; int: ...</p>
              <p>
                &nbsp;&nbsp;def get_flow_at(self, sim_time: datetime) -&gt;
                PassengerFlow: ...
              </p>
              <p className="text-slate-500 mt-2">
                # 3. Register in consumer.py
              </p>
              <p>if self.passenger_source == &quot;bts_historical&quot;:</p>
              <p>&nbsp;&nbsp;self._bts = BTSPassengerSource(csv_path)</p>
              <p className="text-slate-500 mt-2">
                # 4. Add env var in docker-compose.yml
              </p>
              <p>PASSENGER_SOURCE=simulation # or bts_historical</p>
              <p>PASSENGER_BTS_FILE=/app/data/bts/T100_2023.csv</p>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-emerald-900/20 border border-emerald-700/30">
            <h4 className="font-semibold text-emerald-300 mb-1">
              Key Principle
            </h4>
            <p className="text-slate-400 leading-relaxed">
              Downstream services remain unchanged. Any source adapter publishes
              the same canonical Kafka events and writes the same Neo4j entity
              shape. The adapter is a thin translation layer at the system edge.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

/* ──────── Main Page ──────── */

export default function DataSourcesPage() {
  const queryClient = useQueryClient();

  const { data, isLoading, error } = useQuery({
    queryKey: ["data-sources"],
    queryFn: () => dataSourcesApi.list(),
    refetchInterval: 15000,
  });

  const switchMutation = useMutation({
    mutationFn: ({ source }: { sourceId: string; source: string }) =>
      dataSourcesApi.switchWeatherSource(source),
    onSuccess: async () => {
      queryClient.invalidateQueries({ queryKey: ["data-sources"] });
      queryClient.invalidateQueries({ queryKey: ["weather-source"] });
      queryClient.invalidateQueries({ queryKey: ["weather"] });
      // Proactively fetch fresh weather and push it into the global store
      // so the header WeatherStrip updates immediately
      try {
        const fresh = await weatherApi.current();
        if (fresh) {
          useWeatherStore.getState().setCurrent(fresh as WeatherState);
        }
      } catch {
        /* weather will arrive via next WS event */
      }
    },
  });

  const sources = data?.sources ?? [];

  const stats = useMemo(() => {
    const active = sources.filter((s) => s.status === "active").length;
    const degraded = sources.filter((s) => s.status === "degraded").length;
    const unavailable = sources.filter(
      (s) => s.status === "unavailable",
    ).length;
    const realSources = sources.filter(
      (s) =>
        s.current_source !== "simulation" &&
        s.current_source !== "simulated" &&
        s.current_source !== "disabled",
    ).length;
    return {
      active,
      degraded,
      unavailable,
      total: sources.length,
      realSources,
    };
  }, [sources]);

  const handleSwitch = (sourceId: string, newSource: string) => {
    switchMutation.mutate({ sourceId, source: newSource });
  };

  return (
    <div className="h-full overflow-y-auto p-4 sm:p-6 space-y-6">
      {/* Page Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-lg font-bold text-slate-100 flex items-center gap-2">
            <span className="text-xl">🔌</span> Data Sources
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Manage and monitor data providers feeding the digital twin. Switch
            between simulation and real-world sources at runtime.
          </p>
        </div>
        {data && (
          <div className="text-[10px] text-slate-500">
            Last refresh: {new Date(data.timestamp).toLocaleTimeString()}
          </div>
        )}
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
        <div className="rounded-xl bg-slate-800/60 border border-slate-700/40 p-3 text-center">
          <div className="text-lg font-bold text-slate-100">{stats.total}</div>
          <div className="text-[10px] text-slate-400 uppercase tracking-wide">
            Total Sources
          </div>
        </div>
        <div className="rounded-xl bg-emerald-900/30 border border-emerald-700/30 p-3 text-center">
          <div className="text-lg font-bold text-emerald-400">
            {stats.active}
          </div>
          <div className="text-[10px] text-emerald-400/70 uppercase tracking-wide">
            Active
          </div>
        </div>
        <div className="rounded-xl bg-amber-900/30 border border-amber-700/30 p-3 text-center">
          <div className="text-lg font-bold text-amber-400">
            {stats.degraded}
          </div>
          <div className="text-[10px] text-amber-400/70 uppercase tracking-wide">
            Degraded
          </div>
        </div>
        <div className="rounded-xl bg-red-900/30 border border-red-700/30 p-3 text-center">
          <div className="text-lg font-bold text-red-400">
            {stats.unavailable}
          </div>
          <div className="text-[10px] text-red-400/70 uppercase tracking-wide">
            Unavailable
          </div>
        </div>
        <div className="rounded-xl bg-cyan-900/30 border border-cyan-700/30 p-3 text-center">
          <div className="text-lg font-bold text-cyan-400">
            {stats.realSources}
          </div>
          <div className="text-[10px] text-cyan-400/70 uppercase tracking-wide">
            Real-World
          </div>
        </div>
      </div>

      {/* Error state */}
      {error && (
        <div className="rounded-xl bg-red-900/20 border border-red-700/40 p-4 text-sm text-red-300">
          Failed to load data sources: {(error as Error).message}
        </div>
      )}

      {/* Loading state */}
      {isLoading && (
        <div className="text-center text-slate-400 text-sm py-8 animate-pulse">
          Loading data sources...
        </div>
      )}

      {/* Source Cards Grid */}
      {!isLoading && sources.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {sources.map((source) => (
            <SourceCard
              key={source.id}
              source={source}
              onSwitch={handleSwitch}
              isSwitching={switchMutation.isPending}
            />
          ))}
        </div>
      )}

      {/* Switching feedback */}
      {switchMutation.isPending && (
        <div className="fixed bottom-4 right-4 rounded-xl bg-blue-900/90 border border-blue-600/50 px-4 py-3 text-sm text-blue-200 shadow-xl backdrop-blur-sm animate-pulse">
          Switching data source...
        </div>
      )}
      {switchMutation.isError && (
        <div className="fixed bottom-4 right-4 rounded-xl bg-red-900/90 border border-red-600/50 px-4 py-3 text-sm text-red-200 shadow-xl backdrop-blur-sm">
          Switch failed: {(switchMutation.error as Error).message}
        </div>
      )}

      {/* Integration Guide */}
      <IntegrationGuide />
    </div>
  );
}
