#!/usr/bin/env python3
"""Generate destination coordinate lookup for dashboard geospatial views.

This script reads OurAirports CSV data and writes a compact TypeScript module:
`dashboards/art-dashboard/src/data/destinationCoordinates.ts`.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def build_mapping(airports_csv: Path) -> dict[str, tuple[float, float]]:
    mapping: dict[str, tuple[float, float]] = {}
    with airports_csv.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            airport_type = (row.get("type") or "").strip()
            iata = (row.get("iata_code") or "").strip().upper()
            if not iata:
                continue
            if airport_type not in {"large_airport", "medium_airport"}:
                continue
            try:
                lat = float(row["latitude_deg"])
                lon = float(row["longitude_deg"])
            except (TypeError, ValueError, KeyError):
                continue

            # Prefer large_airport coordinates over medium_airport for duplicates.
            if iata in mapping and airport_type == "medium_airport":
                continue
            mapping[iata] = (lat, lon)
    return dict(sorted(mapping.items()))


def write_ts(output_path: Path, mapping: dict[str, tuple[float, float]]) -> None:
    lines = [
        "// Auto-generated by scripts/helper_generate_destination_coordinates.py",
        "// Source: data/ourairports/airports.csv",
        "",
        "export interface DestinationCoordinate {",
        "  lat: number;",
        "  lon: number;",
        "}",
        "",
        "export const DESTINATION_COORDINATES: Record<string, DestinationCoordinate> = {",
    ]

    for iata, (lat, lon) in mapping.items():
        lines.append(f'  "{iata}": {{ lat: {lat:.6f}, lon: {lon:.6f} }},')

    lines.extend(["};", ""])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--airports-csv",
        default="data/ourairports/airports.csv",
        help="Path to OurAirports airports.csv",
    )
    parser.add_argument(
        "--output",
        default="dashboards/art-dashboard/src/data/destinationCoordinates.ts",
        help="Output TypeScript file path",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    airports_csv = Path(args.airports_csv)
    output_path = Path(args.output)

    mapping = build_mapping(airports_csv)
    write_ts(output_path, mapping)
    print(f"Wrote {len(mapping)} destination coordinates to {output_path}")


if __name__ == "__main__":
    main()
