"""Shared data source registry and adapter protocol.

Provides a unified interface for services that support multiple data sources
(simulated, historical, live, etc.) within a theme (weather, passengers,
incidents). Centralizes registration, switching, and listing logic that
was previously duplicated across services.

Usage in a service:

    from _common.data_sources import DataSourceAdapter, DataSourceRegistry

    class MyHistoricalAdapter(DataSourceAdapter):
        source_id = "historical"
        label = "Historical CSV"
        ...

    registry = DataSourceRegistry("weather", env_var="WEATHER_SOURCE", default="simulated")
    registry.register(SimulatedAdapter())
    registry.register(MyHistoricalAdapter(csv_path))
    registry.switch("historical")
"""

from __future__ import annotations

import os
from typing import Protocol, runtime_checkable


@runtime_checkable
class DataSourceAdapter(Protocol):
    """Interface that all data source adapters must implement.

    Adapters are thin translation layers at the system edge — they
    transform external data into the service's canonical internal format.
    Downstream consumers of the data remain unchanged regardless of which
    adapter is active.
    """

    @property
    def source_id(self) -> str:
        """Unique identifier for this source (e.g. 'simulated', 'historical', 'live')."""
        ...

    @property
    def label(self) -> str:
        """Human-readable display name (e.g. 'Iowa State Mesonet CSV')."""
        ...

    @property
    def is_loaded(self) -> bool:
        """Whether the adapter has successfully loaded its data."""
        ...

    def load(self) -> int:
        """Load/initialize data. Returns a count of loaded items (0 for built-in sources)."""
        ...


class SimulatedSourceAdapter:
    """Default adapter for simulation-generated data.

    Always loaded, returns 0 items since data is generated by the
    simulation engine itself rather than loaded from an external source.
    """

    source_id = "simulated"
    label = "Simulation Engine"

    @property
    def is_loaded(self) -> bool:
        return True

    def load(self) -> int:
        return 0


class DataSourceRegistry:
    """Registry for managing multiple data sources within a single theme.

    A theme represents a data domain (weather, passengers, incidents, etc.).
    Each theme can have multiple sources, one of which is active at a time.

    The registry handles:
    - Registration of available adapters
    - Runtime switching between sources
    - Listing available sources with metadata
    - Initialization from environment variables
    """

    def __init__(self, theme: str, *, env_var: str, default: str = "simulated") -> None:
        self.theme = theme
        self._adapters: dict[str, DataSourceAdapter] = {}
        self._active: str = os.getenv(env_var, default)
        self._env_var = env_var

    def register(self, adapter: DataSourceAdapter) -> None:
        """Register an adapter. Can be called multiple times for the same source_id."""
        self._adapters[adapter.source_id] = adapter

    def switch(self, source_id: str, **kwargs) -> dict:
        """Switch to a different data source.

        Returns a dict with {previous, active, loaded_count?} on success.
        Raises ValueError if the source_id is unknown.
        """
        if source_id not in self._adapters:
            available = list(self._adapters.keys())
            raise ValueError(f"Unknown source '{source_id}' for {self.theme}. Available: {available}")

        previous = self._active
        adapter = self._adapters[source_id]

        if not adapter.is_loaded:
            count = adapter.load()
        else:
            count = None

        self._active = source_id
        result = {"previous": previous, "active": source_id, "theme": self.theme}
        if count is not None:
            result["loaded_count"] = count
        return result

    @property
    def active_source(self) -> str:
        """The source_id of the currently active source."""
        return self._active

    def get_active(self) -> DataSourceAdapter | None:
        """Return the active adapter instance, or None if not registered."""
        return self._adapters.get(self._active)

    def get_adapter(self, source_id: str) -> DataSourceAdapter | None:
        """Return a specific adapter by source_id, or None if not registered."""
        return self._adapters.get(source_id)

    def list_sources(self) -> list[dict]:
        """List all registered sources with metadata."""
        return [
            {
                "id": adapter.source_id,
                "label": adapter.label,
                "is_loaded": adapter.is_loaded,
                "active": adapter.source_id == self._active,
            }
            for adapter in self._adapters.values()
        ]

    def info(self) -> dict:
        """Summary of the registry state for REST API responses."""
        active_adapter = self.get_active()
        return {
            "theme": self.theme,
            "active_source": self._active,
            "active_label": active_adapter.label if active_adapter else "unknown",
            "available": self.list_sources(),
        }
