apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arthur-airport

resources:
  - flight-service.yaml
  - passenger-service.yaml
  - baggage-service.yaml
  - weather-service.yaml
  - incident-service.yaml
  - sim-orchestrator.yaml
  - analysis-service.yaml
  - api-gateway.yaml
  - dashboard.yaml
